services:

  experiment-metrla-all:
    hostname: simulator
    image: davidedomini99/experiments-2025-aaai-fedavg-metrla:1.0.1
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [0]

  experiment-metrla-c1:
    hostname: simulator
    image: davidedomini99/experiments-2025-aaai-fedavg-metrla:1.0.1
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [1]

  experiment-metrla-c2:
    hostname: simulator
    image: davidedomini99/experiments-2025-aaai-fedavg-metrla:1.0.1
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [2]

  experiment-metrla-c3:
    hostname: simulator
    image: davidedomini99/experiments-2025-aaai-fedavg-metrla:1.0.1
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [3]

  experiment-metrla-c4:
    hostname: simulator
    image: davidedomini99/experiments-2025-aaai-fedavg-metrla:1.0.1
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [4]

volumes:
  davide.domini-volume:
    external: true
