services:

  experiment-pems-all:
    hostname: pems-all
    image: davidedomini99/experiments-2025-aaai-fedavg-pems:1.0.0
    volumes:
      - davide.domini-volume:/experiment/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [0]

  experiment-pems-c1:
    hostname: pems-c1
    image: davidedomini99/experiments-2025-aaai-fedavg-pems:1.0.0
    volumes:
      - davide.domini-volume:/experiment/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [1]

  experiment-pems-c2:
    hostname: pems-c2
    image: davidedomini99/experiments-2025-aaai-fedavg-pems:1.0.0
    volumes:
      - davide.domini-volume:/experiment/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [2]

  experiment-pems-c3:
    hostname: pems-c3
    image: davidedomini99/experiments-2025-aaai-fedavg-pems:1.0.0
    volumes:
      - davide.domini-volume:/experiment/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [3]

  experiment-pems-c4:
    hostname: pems-c4
    image: davidedomini99/experiments-2025-aaai-fedavg-pems:1.0.0
    volumes:
      - davide.domini-volume:/experiment/data
    environment:
      DATA_OWNER: 1000:1000
      LEARNING_HYPERPARAMETERS: |
        all: 
          cluster: [4]

volumes:
  davide.domini-volume:
    external: true
